### ISSUE TITLE
Название переменной

### ISSUE THREAD

**Issue by SimonOsipov** [sergiishevchenko/lesson1#1]
https://github.com/sergiishevchenko/lesson1/blob/d1ee09f7775cd1b56b4d15d70ed5061e86cec00f/info.py#L26

Пока закроем глаза на то, что это короткое учебное задание, но в коде все переменные должны называть так, чтобы исходя из названия было понятно, что лежит в этой переменной.

`res`- очень неудачное название. Как минимум, лучше назвать `result` =)

**Comment by sergiishevchenko** [comment]
понялю принято!
