### ISSUE TITLE
Приведение типов данных

### ISSUE THREAD

**Issue by SimonOsipov** [sergiishevchenko/lesson1#2]
https://github.com/sergiishevchenko/lesson1/blob/d1ee09f7775cd1b56b4d15d70ed5061e86cec00f/price.py#L2-L3

Зачем тебе дважды приводить тип данных? Ты хотел округлить?)

**Comment by sergiishevchenko** [comment]
сначала нужно ведь округлить, а потом перевести в строчный тип.

**Comment by SimonOsipov** [comment]
К строчному типу можно привести уже когда ты печатаешь. Тамже, к целочисленному.
`f'...{int(price)}....'`
